language: node_js
node_js:
  - "10"
dist: xenial

install:
  - npm install
  - cd syntaxes
  - npm install
  - cd ..

script:
  - npx lix run vshaxe-build -v --debug -t all
  - npx lix run vshaxe-build -v -t vshaxe
