language: node_js
node_js:
  - "10"
dist: xenial

env:
  - HAXE_VERSION=haxerc
  - HAXE_VERSION=nightly

install:
  - npm install
  - cd syntaxes
  - npm install
  - cd ..

script:
  - if [[ "$HAXE_VERSION" == "nightly" ]]; then npx lix use haxe nightly; fi
  - npx lix run vshaxe-build -v --debug -t all
  - npx lix run vshaxe-build -v -t vshaxe
